package com.code.HushChat.security;

import com.code.HushChat.model.ChatRoom;
import com.code.HushChat.realtime.StompConnectAuthInterceptor;
import com.code.HushChat.storage.InMemoryMessageStore;
import com.code.HushChat.storage.InMemoryRoomStore;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.messaging.Message;
import org.springframework.messaging.MessageChannel;
import org.springframework.messaging.simp.stomp.StompCommand;
import org.springframework.messaging.simp.stomp.StompHeaderAccessor;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.HashMap;

import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * End-to-end regression tests for SECURITY FIX #8.
 *
 * <p>Proves that the SAME canonical JWT (generated by {@link JwtTokenProvider})
 * works across both HTTP (via {@link JwtAuthenticationFilter}) and WebSocket /
 * STOMP CONNECT (via {@link StompConnectAuthInterceptor}), for both the OTP /
 * session token flavor (with deviceId) and the room token flavor (no deviceId),
 * and that {@code Principal.getName()} equals the authenticated userId.</p>
 */
@SpringBootTest
@AutoConfigureMockMvc
@TestPropertySource(properties = {
    "app.jwt-secret=1b387c484213ab0f9e0cd8d42385b3a07494b6eac8fc015a9428df27173df4d9",
    "app.jwt-expiration-milliseconds=3600000",
    "hush.jwt.issuer=hush-chat",
    "cors.allowed-origins=http://localhost:8080"
})
class JwtCanonicalAuthenticationTest {

    private static final String ROOM = "ABCXY";
    private static final String ROOM2 = "ROOM2";
    private static final String SESSION_USER_ID = "session-user-123";
    private static final String ROOM_USER_ID = "room-user-456";
    private static final String DEVICE_ID = "device-abc";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @Autowired
    private InMemoryRoomStore roomStore;

    @Autowired
    private InMemoryMessageStore messageStore;

    @BeforeEach
    void seed() {
        roomStore.clear();
        messageStore.clear();
        // Two separate rooms so each token flavor has its own membership.
        roomStore.save(ROOM, new ChatRoom(ROOM, "SessionRoom", SESSION_USER_ID, "SessionUser", 10, 30));
        roomStore.save(ROOM2, new ChatRoom(ROOM2, "RoomRoom", ROOM_USER_ID, "RoomUser", 10, 30));
        roomStore.recordUserJoinTime(ROOM, SESSION_USER_ID);
        roomStore.recordUserJoinTime(ROOM2, ROOM_USER_ID);
    }

    @AfterEach
    void clear() {
        roomStore.clear();
        messageStore.clear();
    }

    // -----------------------------------------------------------------------
    // 11 + 12 + 13. OTP/session token authenticates a protected HTTP endpoint
    //               and Principal.getName() == authenticated userId.
    // -----------------------------------------------------------------------
    @Test
    void sessionTokenAuthenticatesProtectedHttpEndpointAndPrincipalEqualsUserId() throws Exception {
        String sessionToken = jwtTokenProvider.generateToken(
                SESSION_USER_ID, DEVICE_ID, LocalDateTime.now().plusHours(1));

        mockMvc.perform(post("/api/messages/send")
                        .header("Authorization", "Bearer " + sessionToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomCode\":\"" + ROOM + "\",\"content\":\"hello\"}"))
                .andExpect(status().isOk())
                // senderId is derived from Principal.getName() == userId.
                .andExpect(jsonPath("$.data.senderId", is(SESSION_USER_ID)));
    }

    @Test
    void invalidBearerTokenIsRejectedByProtectedHttpEndpoint() throws Exception {
        mockMvc.perform(post("/api/messages/send")
                        .header("Authorization", "Bearer bogus-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomCode\":\"" + ROOM + "\",\"content\":\"hello\"}"))
                .andExpect(status().isUnauthorized());
    }

    // -----------------------------------------------------------------------
    // 15. Existing room token still authenticates a protected HTTP endpoint.
    // -----------------------------------------------------------------------
    @Test
    void roomTokenStillAuthenticatesProtectedHttpEndpoint() throws Exception {
        String roomToken = jwtTokenProvider.generateToken(ROOM_USER_ID);

        mockMvc.perform(post("/api/messages/send")
                        .header("Authorization", "Bearer " + roomToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomCode\":\"ROOM2\",\"content\":\"hi from room\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.senderId", is(ROOM_USER_ID)));
    }

    // -----------------------------------------------------------------------
    // 14. Same canonical session token authenticates STOMP CONNECT.
    // -----------------------------------------------------------------------
    @Test
    void sessionTokenAuthenticatesStompConnect() {
        String sessionToken = jwtTokenProvider.generateToken(
                SESSION_USER_ID, DEVICE_ID, LocalDateTime.now().plusHours(1));

        StompConnectAuthInterceptor interceptor = new StompConnectAuthInterceptor(jwtTokenProvider);
        Message<?> message = createConnectMessage("Bearer " + sessionToken);

        Message<?> result = interceptor.preSend(message, mockChannel());
        assertNotNull(result);
        StompHeaderAccessor accessor = StompHeaderAccessor.wrap(result);
        assertNotNull(accessor.getUser());
        assertEquals(SESSION_USER_ID, accessor.getUser().getName());
    }

    // -----------------------------------------------------------------------
    // 14b. Same canonical room token authenticates STOMP CONNECT.
    // -----------------------------------------------------------------------
    @Test
    void roomTokenAuthenticatesStompConnect() {
        String roomToken = jwtTokenProvider.generateToken(ROOM_USER_ID);

        StompConnectAuthInterceptor interceptor = new StompConnectAuthInterceptor(jwtTokenProvider);
        Message<?> message = createConnectMessage("Bearer " + roomToken);

        Message<?> result = interceptor.preSend(message, mockChannel());
        assertNotNull(result);
        StompHeaderAccessor accessor = StompHeaderAccessor.wrap(result);
        assertNotNull(accessor.getUser());
        assertEquals(ROOM_USER_ID, accessor.getUser().getName());
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------
    private Message<?> createConnectMessage(String authorizationValue) {
        StompHeaderAccessor accessor = StompHeaderAccessor.create(StompCommand.CONNECT);
        accessor.setSessionId("session-1");
        accessor.setLeaveMutable(true);
        accessor.setNativeHeader("Authorization", authorizationValue);
        // Provide session attributes so the interceptor can store the userId.
        accessor.setSessionAttributes(new HashMap<>());
        return MessageBuilder.createMessage(new byte[0], accessor.getMessageHeaders());
    }

    private MessageChannel mockChannel() {
        return new MessageChannel() {
            @Override
            public boolean send(Message<?> message) {
                return true;
            }

            @Override
            public boolean send(Message<?> message, long timeout) {
                return true;
            }
        };
    }
}
